version: "3.3"

services:
  webelexis:
    build: .
    container_name: wlx_webelexis
    hostname: webelexis
    networks:
      - external_webelexis_net
    volumes:
      - ./server/config:/home/node/webelexis/server/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.webelexis.rule=Host(`termine.hodor.lan`)
      - traefik.http.services.service1.loadbalancer.server.port=4040

  traefik:
    image: traefik:v2.8
    container_name: wlx_proxy
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    container_name: simple-service
    labels:
      - traefik.enable=true
      - "traefik.http.routers.eins.rule=Host(`hodor.lan`)"
      - "traefik.http.routers.eins.entrypoints=web"

networks:
  external_webelexis_net:
    external: true
