version: "3.3"

services:
  webelexis:
    build: .
    container_name: wlx_webelexis
    hostname: webelexis
    networks:
      - external_webelexis_net
    volumes:
      - ./server/config:/home/node/webelexis/server/config
    ports:
      - 3030:3030
      - 4040:4040
    labels:
      - traefik.enable=true
      - traefik.http.routers.zwei.rule=Host(`termine.hodor.lan`)
      - traefik.http.routers.zwei.entrypoints=web
      - traefik.http.services.service1.loadbalancer.server.port=4040

  traefik:
    image: traefik:v2.8
    container_name: wlx_proxy
    command:
      - --log.level=DEBUG
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  external_webelexis_net:
    driver: bridge
