openapi: 3.0.2
info:
  title: Webelexis Server
  version: 1.0.0

servers:
  - url: http://localhost:3030

paths:
  /termin/types:
    get:
      summary: retrieve list of possible event /temin/types
      responses:
        default:
          description: An Array of strings
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /termin/states:
    get:
      summary: retrieve list of pssible event /termin/states
      responses:
        default:
          $ref: "#/components/stringarray"

  /termin/{id}:
    get:
      summary: Returns an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
              type: string
      responses:
        '200':
          description: returns an event object
          content:
            application/json:
              schema:
                $ref: openapi/schemas/event.yaml
        '404':
          description: not found



components:
  schemas:
    event:
      $ref: openapi/schemas/event.yaml


    stringarray:
      default:
      description: An Array of strings
      content:
        application/json:
          schema:
            type: array
            items:
              type: string


