openapi: 3.0.2
info:
  title: Webelexis Server
  version: 3.7.3

servers:
  - url: http://localhost:3030

paths:
  /termin/statecolors:
    get:
      summary: get colors by state
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: User, who's color preferences are requested
      responses:
        "200":
          description: OK
  /termin/typecolors:
    get:
      summary: get colors by type
      parameters:
        - in: query
          name: user
          schema:
            type: string
          description: User, who's color preferences are requested
      responses:
        "200":
          description: OK

  /termin/timedefaults:
    get:
      summary: retrieve default duration per event type
      responses:
        default:
          $ref: "#components/responses/timedefaults"

  /termin/daydefaults:
    get:
      description: retrieve default schedulable times per weekday
      parameters:
        - in: query
          name: resource
          schema:
            type: string
          description: resource for which daydefaults are needed

      responses:
        default:
          $ref: "#components/responses/daydefaults"

  /termin/resources:
    get:
      description: list of resources to manage
      responses:
        default:
          $ref: "#components/responses/stringarray"

  /termin/types:
    get:
      summary: retrieve list of possible event types
      responses:
        default:
          $ref: "#components/responses/stringarray"

  /termin/states:
    get:
      summary: retrieve list of pssible event states
      responses:
        default:
          $ref: "#components/responses/stringarray"

  /termin/{id}:
    get:
      summary: Returns an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: returns an event object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/event'
        "404":
          description: not found

components:
  schemas:
    event:
      $ref: schemas/event.yaml#/event
    finding:
      $ref: schemas/finding.yaml#/finding

  responses:
    stringarray:
      description: Array of Strings
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
    daydefaults:
      description: Default open times per day and resource
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true

    timedefaults:
      description: Default duration per event type
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
